"""Paleta y medidas reutilizables."""

from manim import BLUE_D, GREEN, GREY_B, WHITE, YELLOW

COLOR_NODO = BLUE_D
COLOR_DATO = WHITE
COLOR_PUNTERO = YELLOW
COLOR_NULL = GREY_B
COLOR_RESALTADO = GREEN
ANCHO_NODO = 1.45
ALTO_NODO = 0.85
ESPACIO_NODOS = 0.8
